# Generated by Django 4.0.6 on 2022-08-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('vacunas', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(null=True, upload_to='mascota')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=30)),
                ('nacimiento', models.DateField()),
                ('pais', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=20)),
                ('celular', models.IntegerField()),
                ('entidad', models.CharField(max_length=50)),
            ],
        ),
    ]
