# Generated by Django 4.0.6 on 2022-08-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
