# Generated by Django 4.0.6 on 2022-08-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primApp', '0002_alter_mascotas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='descripcion',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='edad',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='vacunas',
            field=models.TextField(max_length=150),
        ),
    ]
