# Generated by Django 4.0.5 on 2022-08-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primApp', '0003_usuarios_imagen_alter_mascotas_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='vacunas',
            field=models.CharField(max_length=60),
        ),
    ]
